# This file was generated by GoReleaser. DO NOT EDIT.
class Gosimac < Formula
  desc "Fetch the wallpaper from Bings, Unsplash ..."
  homepage ""
  version "4.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/1995parham/gosimac/releases/download/v4.0.3/gosimac_4.0.3_darwin_amd64.tar.gz"
    sha256 "071d0e96d67c795d7b5b4b0f35e64a8e1accaf81088a5c46a3fe59afa3646d42"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/1995parham/gosimac/releases/download/v4.0.3/gosimac_4.0.3_linux_amd64.tar.gz"
      sha256 "b74e4fa4c6afedb6fb8035f7bec984f4b6daa0408f270130bf45bee077c74b68"
    end
  end

  def install
    bin.install "gosimac"
  end
end
