# This file was generated by GoReleaser. DO NOT EDIT.
class Gosimac < Formula
  desc "Fetch the wallpaper from Bings, Unsplash ..."
  homepage "https://github.com/1995parham/gosimac"
  version "4.1.1"

  if OS.mac?
    url "https://github.com/1995parham/gosimac/releases/download/v4.1.1/gosimac_4.1.1_darwin_amd64.tar.gz"
    sha256 "d97c210726aa33973c5414c4ddcd6cd017c4f697ba0f299503b0d0de2a6353cd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/1995parham/gosimac/releases/download/v4.1.1/gosimac_4.1.1_linux_amd64.tar.gz"
      sha256 "a8e399597f0058c434d068916a6f4849559aabe3e4a94f531950dbfd4e015374"
    end
  end

  def install
    bin.install "gosimac"
  end
end
