# This file was generated by GoReleaser. DO NOT EDIT.
class Zamaneh < Formula
  desc "Manage your working periods with ease"
  homepage ""
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/1995parham/zamaneh/releases/download/v0.0.1/gosimac_0.0.1_darwin_amd64.tar.gz"
    sha256 "7942ca4a4be60c158c153582eb597988cd3aa60bc310a80441aaa10f0cd9ab26"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/1995parham/zamaneh/releases/download/v0.0.1/gosimac_0.0.1_linux_amd64.tar.gz"
      sha256 "38ed96492f4b0db165560c900f42b68de493480d9ac47cc2e65e24570a0d1bd5"
    end
  end

  def install
    bin.install "gosimac"
  end
end
